"""initial commit

Revision ID: 14f94f54f8ed
Revises: 
Create Date: 2024-08-01 17:04:03.844075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f94f54f8ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('tender_details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_timestamp'), ['timestamp'], unique=False)

    op.create_table('job_seeker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=3), nullable=True),
    sa.Column('unique_id', sa.String(length=6), nullable=True),
    sa.Column('documents', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    with op.batch_alter_table('job_seeker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_seeker_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_seeker_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_seeker_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_seeker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_seeker_timestamp'))
        batch_op.drop_index(batch_op.f('ix_job_seeker_name'))
        batch_op.drop_index(batch_op.f('ix_job_seeker_email'))

    op.drop_table('job_seeker')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_timestamp'))
        batch_op.drop_index(batch_op.f('ix_company_name'))
        batch_op.drop_index(batch_op.f('ix_company_email'))

    op.drop_table('company')
    # ### end Alembic commands ###
